### ISSUE TITLE
generate.py

### ISSUE THREAD

**Issue by fitrialif** [huseinzol05/Bahasa-NLP-Tensorflow#1]
after I install malaya, this error come when I import malaya

AttributeError: type object 'Path' has no attribute 'home'

**Comment by huseinzol05** [comment]
`Path.home()` introduced in Python 3.5, and Malaya required Python 3.6.X and above, or else you might break the library, stated here, https://github.com/huseinzol05/malaya.
`Only Python 3.6.x and above and Tensorflow 1.X are supported.`
